### ISSUE TITLE
How do I set the type of registry key?

### ISSUE THREAD

**Issue by i2i8** [AonaSuzutsuki/ExRegistryHive#1]
Hi,Can you show me an example of setting the registry to "REG_SZ", "REG_MULTI_SZ", "REG_EXPAND_SZ", "REG_DWORD", "REG_QWORD", or "REG_BINARY" ?

**Comment by AonaSuzutsuki** [comment]
To specify a specific type, specify "dwType", the fourth argument of "RegSetValueExA function".
Please refer to the official documentation for the type values.

[RegistryValueKind Enum - Microsoft Docs](https://docs.microsoft.com/en-us/dotnet/api/microsoft.win32.registryvaluekind?view=net-5.0)  
[Registry Value Types - Microsoft Docs](https://docs.microsoft.com/en-us/windows/win32/sysinfo/registry-value-types)  

I'm sorry, I haven't updated the site in a long time, so I don't know the details.

**Comment by i2i8** [comment]
I tried to debug according to your instructions, but failed. Can you give me an example?

**Comment by i2i8** [comment]
I tried to debug according to your instructions, but failed. Can you give me an example?

**Comment by AonaSuzutsuki** [comment]
Please refer to "ExSetValue method" in "ExRegistry.cs".  
I'm sorry, I'm too busy to write the sample code.

[ExRegistry.cs](https://github.com/AonaSuzutsuki/ExRegistryHive/blob/master/ExRegistryHiveLib/ExRegistry.cs)

**Comment by AonaSuzutsuki** [comment]
This is a thread that hasn't been running for a long time, so I'm closing it.
